### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by ghost** [dillongoostudios/goo-blender#10]
Any chance that features in goo-engine get merged into blender?

**Comment by FriskTheFallenHuman** [comment]
From the readme:

`Some have asked why we haven't pushed these changes to Blender's master branch: this is because many of these features would not be accepted as they are and may destablize other features like Cycles. We only use Eevee for NPR so we prioritize specific features which the Blender Institute understandably can't afford to make compromises for. This allows us to develop and test quickly. However, we do actively update Goo Engine to keep up with the native Blender branch so they can evolve side by side. We also regularly add and improve custom features as we use Goo Engine on projects at the studio. [Stay tuned](https://twitter.com/dillongoostudio) for updates.`

while yes we would love to have these merge into blender, so sadly no, unless someone tries to get these changes to upstream
