### ISSUE TITLE
SSGI

### ISSUE THREAD

**Issue by xxxmf** [dillongoostudios/goo-blender#16]
goo-engine is useful outside NPR scope because of light groups it makes lighting much easier to work with. Any chance you could merge or implement SSGI ? Or you want to stick just NPR related and nothing else? If goo-engine had SSGI it would be a game changer really in terms of EEVEE usability

**Comment by Lateasusual** [comment]
For a small amount of time we actually had the SSGI patch merged, but we never used it in our workflow and removed it eventually to simplify maintenance. As such there's no plans to merge the SSGI patch at the moment - it's also quite a long way out of date, since there's plans for some version of SSGI in the new EEVEE version which won't be compatible with goo-engine either.
