### ISSUE TITLE
the light and shadow dont respne

### ISSUE THREAD

**Issue by Sakurasao** [dillongoostudios/goo-blender#17]
https://drive.google.com/file/d/1JSq9TLJd9Kr2R1btC1Um6rvTyxHyaoVA/view?usp=sharing
anyone can help me with this error, I don't know what's wrong in texture shading or this blender

**Comment by Floreum** [comment]
It's not an error, this is because you are using an emission shader node at the end which gets rid of all shadows since it's emitting light. You aren't even using the nodes that this branch provides that would add shadows to this. Here's a basic example setup.  ![2022-11-26_16-29-54](https://user-images.githubusercontent.com/12518522/204112592-eeca6876-a867-438b-8844-9fac00b62435.png)

I would suggest looking at [Dillon Goo's tutorial](https://youtu.be/PBdvcP8WhX8) on how to use this branch of Blender.

**Comment by Sakurasao** [comment]
ok thanks i will try again, sorry for the misunderstanding

**Comment by Sakurasao** [comment]
![Screenshot 2022-11-27 212707](https://user-images.githubusercontent.com/71950711/204140577-cc7f5e87-2ebf-4561-8d2d-d254c49de32e.jpg)
![Screenshot 2022-11-27 212639](https://user-images.githubusercontent.com/71950711/204140579-42d9346a-0199-4035-98ac-6e7850ddc2e8.jpg)
can anyone help me on this?, if i turn off the shadow on the lamp it works otherwise if i turn on the shadow on the lamp then it doesn't work
