### ISSUE TITLE
Cycles won't run on gpu

### ISSUE THREAD

**Issue by Fluffpumpkin** [dillongoostudios/goo-blender#26]
If I try to run cycles on the cpu it runs just fine but is slow (like cpu usually is). When I try to run it on the gpu I get an error. It works just fine in regular blender, the problem is only with the goo engine. Is this my fault or is it a bug?
``` CUDA version 11.8 detected, build may succeed but only CUDA 10.1 to 11.4 are officially supported.
Compiling CUDA kernel ...
"nvcc" -arch=sm_86 --cubin "D:\goo-blender-master\3.4\scripts\addons\cycles\source\kernel\device\cuda\kernel.cu" -o "C:\Users\surfl\AppData\Roaming\Blender Foundation\Blender\3.4\cache\kernels\cycles_kernel_sm_86_904C389680A13667F33E6AFB16ED8E03.cubin" -m64 --ptxas-options="-v" --use_fast_math -DNVCC -I"D:\goo-blender-master\3.4\scripts\addons\cycles\source" -DWITH_NANOVDB
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
Failed to execute compilation command, see console for details.

Refer to the Cycles GPU rendering documentation for possible solutions:
https://docs.blender.org/manual/en/latest/render/cycles/gpu_rendering.html

**Comment by Lateasusual** [comment]
Since we don't use Cycles (and goo-engine has no features which affect or support Cycles) the we don't pre-compile the GPU kernels for it. 
The simplest option is to just use a regular blender build, since there shouldn't be any benefit to using cycles in goo-engine either way. 

Alternatively if you really need to use goo-engine you can let it compile the GPU kernels for you, if you install Visual Studio 2019/2022 and CUDA 11 (and also OptiX SDK7.3+ if you want OptiX support) then switching to GPU compute will compile the kernel the first time you switch to render view. You'll see something like "Loading render kernels (may take a few minutes the first time)" in the top left of the viewport.
