### ISSUE TITLE
Is there a step by step guide on how to run this on Windows 11?

### ISSUE THREAD

**Issue by a-notperson** [dillongoostudios/goo-blender#9]
I have no idea what I'm doing when it comes to trying to install this, would someone please be able to help?

**Comment by letsblazelbc** [comment]
I need help also, I never installed an addon using the source code.  Can anyone point us in the right direction please ?

**Comment by xxxmf** [comment]
for windows:

Step 0: read this: https://wiki.blender.org/wiki/Building_Blender/Windows

Step 1: make sure all the requirements are properly installed, if you skipped any instruction like adding git and cmake to path then "make update" wont work
Step 2: create an empty folder, run cmd and cd to that empty folder then run "git clone https://github.com/dillongoostudios/goo-engine.git" . make sure the folder is empty
step 3: cd to the new "goo-engine" folder, run "make update", if asks to download type "y" press enter. repeat this step TWICE
step 4: in this new folder run "make" not nmake. it will create a new folder called "build_windows_x64_vc17_Release", inside you have a folder called "bin", after the compilation is done you will find final blender files inside you can copy paste it somewhere else. first compilation takes a long time even if you have a good cpu and during complation your pc may become unusable.
step 5: if something errors and above steps dont fix it then delete everything and start over
step 6: to update simply repeat "make update" and "make", update compilations should be quick
step 7: if anything errors or breaks, delete everything and start over.

at the end your empty folder should have 3 folders like this:

goo-engine
build_windows_x64_vc17_Release
lib

you can find blender files, like the ones you download, inside yourfolder/build_windows_x64_vc17_Release/bin/Release/

the whole process take 15+gb of space with over 80000 files, ssd is recommended

if you can spare 5$ at https://www.patreon.com/dillongoo to get a download link i think its really worth it because this is too much trouble for most people especially how easy it is to mess it up you can easily lose days trying to build it, but if you have no other option then - good luck!

**Comment by pftq** [comment]
Also just in case it saves anyone else time, make sure to:
1) install [Git for Windows](https://gitforwindows.org/), not Github for Windows - not the same thing and won't work without Git for Windows.
2) install VC 2019 (for now).  More of a precaution, as I had trouble compiling with version 2022 and read it as a suggestion in the thread here https://github.com/dillongoostudios/goo-engine/issues/4#issuecomment-1310779710

**Comment by Zo0m4ek** [comment]
> for windows:
> 
> Step 0: read this: https://wiki.blender.org/wiki/Building_Blender/Windows
> 
> Step 1: make sure all the requirements are properly installed, if you skipped any instruction like adding git and cmake to path then "make update" wont work Step 2: create an empty folder, run cmd and cd to that empty folder then run "git clone https://github.com/dillongoostudios/goo-engine.git" . make sure the folder is empty step 3: cd to the new "goo-engine" folder, run "make update", if asks to download type "y" press enter. repeat this step TWICE step 4: in this new folder run "make" not nmake. it will create a new folder called "build_windows_x64_vc17_Release", inside you have a folder called "bin", after the compilation is done you will find final blender files inside you can copy paste it somewhere else. first compilation takes a long time even if you have a good cpu and during complation your pc may become unusable. step 5: if something errors and above steps dont fix it then delete everything and start over step 6: to update simply repeat "make update" and "make", update compilations should be quick step 7: if anything errors or breaks, delete everything and start over.
> 
> at the end your empty folder should have 3 folders like this:
> 
> goo-engine build_windows_x64_vc17_Release lib
> 
> you can find blender files, like the ones you download, inside yourfolder/build_windows_x64_vc17_Release/bin/Release/
> 
> the whole process take 15+gb of space with over 80000 files, ssd is recommended
> 
> if you can spare 5$ at https://www.patreon.com/dillongoo to get a download link i think its really worth it because this is too much trouble for most people especially how easy it is to mess it up you can easily lose days trying to build it, but if you have no other option then - good luck!

Please help! When I trying to run "make update", cmd showed me "There are spaces detected in the build path "E:\GameDev\build blender\blender\goo-engine\", this is currently not supported, exiting....". How to solve this?

(P.S. Folder isn't empty, idk what I need to do with this...)

**Comment by pftq** [comment]
Try renaming your "build blender" folder to "build-blender" so there is no space.

**Comment by Zo0m4ek** [comment]
> Try renaming your "build blender" folder to "build-blender" so there is no space.

Thanks a lot.

**Comment by Zo0m4ek** [comment]
Well, I have another problem... 

"E:\GameDev\blender_build\goo-engine>make
No explicit msvc version requested, autodetecting version.
** Visual Studio 2019 Developer Command Prompt v16.11.12
** Copyright (c) 2021 Microsoft Corporation
[vcvarsall.bat] Environment initialized for: 'x64'
Compiler Detection successful, detected VS2019
Cmake not found in path, required for building, exiting..."

The problem is solved. Just needed to restart PC after installing CMake.

**Comment by Askysoul** [comment]
> Well, I have another problem...
> 
> "E:\GameDev\blender_build\goo-engine>make No explicit msvc version requested, autodetecting version. ** Visual Studio 2019 Developer Command Prompt v16.11.12 ** Copyright (c) 2021 Microsoft Corporation [vcvarsall.bat] Environment initialized for: 'x64' Compiler Detection successful, detected VS2019 Cmake not found in path, required for building, exiting..."
> 
> The problem is solved. Just needed to restart PC after installing CMake.

ahh dude use choco to install this and add to system path

 choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

**Comment by PurpBatBoi** [comment]
this should have pre-built builds instead of having to build manually

**Comment by Askysoul** [comment]
> this should have pre-built builds instead of having to build manually

i builded it its in my repos if you want you can have it

**Comment by pftq** [comment]
It's pre-built and available to download on the Patreon page.  It's a soft incentive to support their dev team. https://www.patreon.com/dillongoo

**Comment by PurpBatBoi** [comment]
> It's pre-built and available to download on the Patreon page. It's a soft incentive to support their dev team. https://www.patreon.com/dillongoo

It's nice to support the devs and all but then why release the code and leave users to troubleshoot for hours and possibly with no build, Blender do have a guide to compile it but Alot of things can to wrong in the process

**Comment by pftq** [comment]
Probably it should be made clear on the readme/github homepage.  The main
link to this is https://gooengine.org/ which does point to the Patreon as
the main download (and github only if you want the source).

**Comment by Askysoul** [comment]
> It's pre-built and available to download on the Patreon page. It's a soft incentive to support their dev team. https://www.patreon.com/dillongoo

oh i didnot know that

**Comment by The-Architekt** [comment]
I ran into another problem, I forgot I can run "make update" twice and "make" once in order to update it and instead I deleted all the files (so i could reinstall the new version). When I was reinstalling it I ran into an issue where it will say "python not found, required for this operation". This appears after running "make update" then typing "y". Would anyone happen to know how to fix this?
